name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.15.2
          run_install: |
            - recursive: true
      - run: pnpm recursive run build
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.15.2
          run_install: |
            - recursive: true
      - run: pnpm run build:config
      - run: pnpm run fmt:ci
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.15.2
          run_install: |
            - recursive: true
      - run: pnpm run build:config
      - run: pnpm run lint:ci
